spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /html/
      suffix: .html
  main:
    # Spring Boot 2.1 需要显式开启bean override
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.adtec.**.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:conf/logback.xml